This notebook is a prototype of the rTMS Bayesian Optimization algorithm and will reflect the final step of pipeline after tetrahedral projection and FEM surface construction/registration

In [1]:
import os
import numpy as np
from fieldopt import geolib
from fieldopt.objective import FieldFunc
from timeit import default_timer as timer

In [2]:
#MOE package loading (should wrap!)
from moe.optimal_learning.python.cpp_wrappers.domain import TensorProductDomain as cTensorProductDomain
from moe.optimal_learning.python.python_version.domain import TensorProductDomain
from moe.optimal_learning.python.geometry_utils import ClosedInterval
from moe.optimal_learning.python.cpp_wrappers.expected_improvement import ExpectedImprovement
from moe.optimal_learning.python.cpp_wrappers.expected_improvement import multistart_expected_improvement_optimization as meio
from moe.optimal_learning.python.data_containers import HistoricalData, SamplePoint
from moe.optimal_learning.python.cpp_wrappers.log_likelihood_mcmc import GaussianProcessLogLikelihoodMCMC
from moe.optimal_learning.python.default_priors import DefaultPrior
from moe.optimal_learning.python.python_version.optimization import GradientDescentOptimizer, GradientDescentParameters
from moe.optimal_learning.python.cpp_wrappers.optimization import GradientDescentOptimizer as cGDOpt
from moe.optimal_learning.python.cpp_wrappers.optimization import GradientDescentParameters as cGDParams

In [3]:
#Specify inputs
proj_dir =  '/rtms_optimize'
mesh_file = os.path.join(proj_dir,'data','simnibs_output','sub-CMH090.msh')
coil_file = os.path.join(proj_dir,'resources','coils','Magstim_70mm_Fig8.nii.gz')
tet_file = os.path.join(proj_dir,'output','tetra_parcels')
C_file = os.path.join(proj_dir,'output','quadratic_vec')
iR_file = os.path.join(proj_dir,'output','inverse_rot')
b_file = os.path.join(proj_dir,'output','param_bounds')
testing_dir = '/tmp/'#os.path.join(proj_dir,'testing','tmp')

In [4]:
#Step 1: Load in files containing relevant information about search domain
C = np.fromfile(C_file)
iR = np.fromfile(iR_file).reshape(3,3)
b = np.fromfile(b_file).reshape(3,2)

#Load in element mask
p_map = np.load(os.path.join(proj_dir,'output','tetra_parcels.npy'))[:,2]

In [5]:
#Step 2: Specify the search domain
search_domain = TensorProductDomain([
    ClosedInterval(b[0,0],b[0,1]), #X coord on quadratic surface
    ClosedInterval(b[1,0],b[1,1]), #Y coord on quadratic surface
    ClosedInterval(0,180) #Rotational angle
])

c_search_domain = cTensorProductDomain([
    ClosedInterval(b[0,0],b[0,1]), 
    ClosedInterval(b[1,0],b[1,1]),
    ClosedInterval(0,180)
])

In [6]:
#Make objective function
ncpus = 15
f = FieldFunc(mesh_file=mesh_file, quad_surf_consts=C,
              surf_to_mesh_matrix=iR, tet_weights=p_map,
              field_dir=testing_dir, coil=coil_file, cpus=ncpus)

In [17]:
#Generate historical data 
hist_pts = int(ncpus * 1.5)
init_pts = search_domain.generate_uniform_random_points_in_domain(hist_pts)
start = timer()
observations = f.evaluate(init_pts)
stop = timer()
print(stop - start)

[ simnibs ]INFO: Could not find the dti tensor file in the standard location: /rtms_optimize/data/simnibs_output/d2c_sub-CMH090/dti_results_T1space/DTI_conf_tensor.nii.gz
[ simnibs ]INFO: Head Mesh: /rtms_optimize/data/simnibs_output/sub-CMH090.msh
[ simnibs ]INFO: Subject Path: /rtms_optimize/data/simnibs_output/m2m_sub-CMH090
[ simnibs ]INFO: Simulation Folder: /tmp/tmp2934Vq
[ simnibs ]INFO: Running simulations in the directory: /tmp/tmp2934Vq
[ simnibs ]INFO: Running Poslist Number: 1
[ simnibs ]INFO: Began to run TMS simulations
[ simnibs ]INFO: Using coil: /rtms_optimize/resources/coils/Magstim_70mm_Fig8.nii.gz
[ simnibs ]INFO: Using isotropic conductivities


0
1


[ simnibs ]INFO: Running TMS Position 0


2


[ simnibs ]INFO: Coil Position Matrix: [[ 1.58074002e-02 -5.86537061e-01  8.09768116e-01 -6.03975757e+01]
 [ 2.90441884e-01 -7.72255509e-01 -5.65035345e-01  6.84103810e+01]
 [-9.56762059e-01 -2.44122317e-01 -1.58147577e-01  1.39553722e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 1


3


[ simnibs ]INFO: Coil Position Matrix: [[-7.10172334e-01  6.09560308e-02  7.01384073e-01 -5.59957146e+01]
 [-6.10211657e-01 -5.50175390e-01 -5.70042783e-01  6.51972604e+01]
 [-3.51136710e-01  8.32821351e-01 -4.27915421e-01  3.16170110e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 2


4


[ simnibs ]INFO: Coil Position Matrix: [[  0.18957529  -0.5234234    0.83071605 -70.14265611]
 [  0.81839132  -0.38322133  -0.42822548  42.80664241]
 [ -0.54249135  -0.76103177  -0.35571587  32.48474273]
 [  0.           0.           0.           1.        ]]
dIdt: 1000000.0



5


[ simnibs ]INFO: Running TMS Position 3
[ simnibs ]INFO: Coil Position Matrix: [[-7.46541563e-01  3.37969286e-01  5.73107718e-01 -4.66236924e+01]
 [-6.61895169e-01 -4.64779667e-01 -5.88111084e-01  6.86796955e+01]
 [-6.76053310e-02  8.18386597e-01 -5.70677577e-01  3.94943855e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 4


6


[ simnibs ]INFO: Coil Position Matrix: [[ -0.6154857   -0.33178052   0.71491191 -55.1005968 ]
 [ -0.28366389  -0.75303969  -0.59368849  69.51113326]
 [ -0.73533132   0.56820147  -0.36937101  26.91063918]
 [  0.           0.           0.           1.        ]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 5


7


[ simnibs ]INFO: Coil Position Matrix: [[ -0.75623527  -0.15776645   0.63499446 -55.95747234]
 [ -0.24131383  -0.83482734  -0.49480395  52.45273296]
 [ -0.6081742    0.52742114  -0.59325465  44.91271405]
 [  0.           0.           0.           1.        ]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 6
[ simnibs ]INFO: Coil Position Matrix: [[-4.50567102e-02 -7.37637664e-01  6.73691747e-01 -5.68165081e+01]
 [ 6.69369338e-01 -5.22892743e-01 -5.27757395e-01  5.79117753e+01]
 [-7.41562258e-01 -4.27169587e-01 -5.17311862e-01  3.88796640e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0



8


[ simnibs ]INFO: Running TMS Position 7


9


[ simnibs ]INFO: Coil Position Matrix: [[  0.22676414  -0.39449341   0.89047907 -70.98647004]
 [  0.61139905  -0.65404189  -0.44544405  50.58604777]
 [ -0.75813536  -0.6454488   -0.09287965  13.84416123]
 [  0.           0.           0.           1.        ]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 8


10


[ simnibs ]INFO: Coil Position Matrix: [[-3.93804015e-01  2.97840346e-01  8.69603085e-01 -7.40184130e+01]
 [-9.18853723e-01 -1.01798589e-01 -3.81241239e-01  3.56485871e+01]
 [ 2.50246560e-02  9.49172363e-01 -3.13760404e-01  3.12921944e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 9


11


[ simnibs ]INFO: Coil Position Matrix: [[  0.29610529  -0.54104209   0.78714364 -68.34793226]
 [  0.90063571  -0.11628631  -0.41872762  40.13746435]
 [ -0.31808329  -0.83291713  -0.45284884  38.87070193]
 [  0.           0.           0.           1.        ]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 10


12


[ simnibs ]INFO: Running TMS Position 11
[ simnibs ]INFO: Coil Position Matrix: [[-1.46827080e-01 -5.29583471e-01  8.35453862e-01 -6.07303365e+01]
 [-1.79377960e-01 -8.16348605e-01 -5.48997725e-01  6.95121236e+01]
 [-9.72761716e-01  2.30469742e-01 -2.48664795e-02  4.11546835e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0



13


[ simnibs ]INFO: Coil Position Matrix: [[-8.51590310e-01  5.31805147e-02  5.21503382e-01 -4.63881230e+01]
 [-3.65662605e-01 -7.73100581e-01 -5.18272468e-01  5.76449191e+01]
 [-3.75612571e-01  6.32050097e-01 -6.77811089e-01  4.94517616e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0



14


[ simnibs ]INFO: Running TMS Position 12
[ simnibs ]INFO: Coil Position Matrix: [[-2.48718116e-01 -6.19546930e-01  7.44513868e-01 -5.48131701e+01]
 [ 1.15705693e-01 -7.82169239e-01 -6.12228285e-01  7.38546461e+01]
 [-9.61640001e-01  6.61277725e-02 -2.66224767e-01  1.93254373e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 13
[ simnibs ]INFO: Coil Position Matrix: [[-1.79081407e-01 -4.18036112e-01  8.90604098e-01 -7.00872759e+01]
 [-2.56837838e-01 -8.53982520e-01 -4.52491084e-01  5.29839971e+01]
 [-9.49717945e-01  3.09773571e-01 -4.55648999e-02  9.84839631e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
dIdt: 1000000.0

[ simnibs ]INFO: Running TMS Position 14
[ simnibs ]INFO: Coil Position Matrix: [[ -0.51698486   0.62215346   0.58792153 -53.50234228]
 [ -0.8430085   -0.25087156  -0.47581523  49.52378888]
 [  0.1485373    0.74161211  -0.65417745  49.59411127]
 [  0.           0.    

[ simnibs ]INFO: Info    : Started (Fri Apr 26 16:10:03 2019, Wall = 0.000180006s, CPU = 0.004543s, Mem = 5.17578Mb)
[ simnibs ]INFO: Info    : Initializing Gmsh
[ simnibs ]INFO: Info    : Loading problem definition '/tmp/tmp2934Vq/sub-CMH090_TMS_1-0007_Magstim_70mm_Fig8_nii.pro'
[ simnibs ]INFO: Info    : Selected Resolution 'QS'
[ simnibs ]INFO: Info    : Loading Geometric data '/tmp/tmp2934Vq/tmp35NNXx.msh'
[ simnibs ]INFO: Info    : Mesh is in binary format
[ simnibs ]INFO: Info    : Running '/simnibs/bin/getdp /tmp/tmp2934Vq/sub-CMH090_TMS_1-0009_Magstim_70mm_Fig8_nii.pro -solve QS -msh /tmp/tmp2934Vq/tmp2rE5QT.msh -ksp_type cg -ksp_rtol 1e-10 -pc_type icc -pc_factor_levels 2 -v2 -bin' [GetDP 2.11.3, 1 node, max. 1 thread]
[ simnibs ]INFO: Info    : Started (Fri Apr 26 16:10:03 2019, Wall = 0.000184059s, CPU = 0.004333s, Mem = 5.33594Mb)
[ simnibs ]INFO: Info    : Initializing Gmsh
[ simnibs ]INFO: Info    : Loading problem definition '/tmp/tmp2934Vq/sub-CMH090_TMS_1-0009_Magstim_

[ simnibs ]INFO: Info    : Selected Resolution 'QS'
[ simnibs ]INFO: Info    : Initializing Gmsh
[ simnibs ]INFO: Info    : Loading Geometric data '/tmp/tmp2934Vq/tmpQuxil4.msh'
[ simnibs ]INFO: Info    : Loading problem definition '/tmp/tmp2934Vq/sub-CMH090_TMS_1-0006_Magstim_70mm_Fig8_nii.pro'
[ simnibs ]INFO: Info    : Mesh is in binary format
[ simnibs ]INFO: Info    : Selected Resolution 'QS'
[ simnibs ]INFO: Info    : Loading Geometric data '/tmp/tmp2934Vq/tmpe4IRvR.msh'
[ simnibs ]INFO: Info    : Mesh is in binary format
[ simnibs ]INFO: Info    : System 'QS_dAdt' : Real
[ simnibs ]INFO: P r e - P r o c e s s i n g . . .
[ simnibs ]INFO: Info    : Treatment Formulation 'QS_Formulation'
[ simnibs ]INFO: Info    : System 'QS_dAdt' : Real
[ simnibs ]INFO: P r e - P r o c e s s i n g . . .
[ simnibs ]INFO: Info    : Treatment Formulation 'QS_Formulation'
[ simnibs ]INFO: Info    : System 'QS_dAdt' : Real
[ simnibs ]INFO: P r e - P r o c e s s i n g . . .
[ simnibs ]INFO: Info    : T

[ simnibs ]INFO: Info    : GmshRead[/tmp/tmp2934Vq/sub-CMH090_TMS_1_cond.msh] -> View[1]
[ simnibs ]INFO: Info    : Reading nodes
Info    : System 1/1: 657584 Dofs                                                  
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : No current model available: creating one
[ simnibs ]INFO: Info    : Reading '/tmp/tmp2934Vq/sub-CMH090_TMS_1_cond.msh'...
[ simnibs ]INFO: Info    : 657584 vertices
[ simnibs ]INFO: Info    : Reading nodes
Info    : System 1/1: 657584 Dofs                                                  
[ simnibs ]INFO: Info    : (Wall = 10.277s, CPU = 9.80699s, Mem = 588.262Mb)
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: E n d   P r e - P r o c e s s i n g
[ simnibs ]INFO: P r o c e s s i n g . . .
[ simnibs ]INFO: Info    : GmshRead[/tmp/tmp293

[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Readi

[ simnibs ]INFO: Info    : Reading '/tmp/tmp2934Vq/sub-CMH090_TMS_1-0007_Magstim_70mm_Fig8_nii_dadt.msh'...
[ simnibs ]INFO: Info    : 657584 vertices
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading data
[ simnibs ]INFO: Info    : Done reading '/tmp/tmp2934Vq/sub-CMH090_TMS_1_cond.msh'
[ simnibs ]INFO: Info    : GmshRead[/tmp/tmp2934Vq/sub-CMH090_TMS_1-0002_Magstim_70mm_Fig8_nii_dadt.msh] -> View[2]
[ simnibs ]INFO: Info    : Reading '/tmp/tmp2934Vq/sub-CMH090_TMS_1-0002_Magstim_70mm_Fig8_nii_dadt.msh'...
[ simnibs ]INFO: Info    : 657584 vertices
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading data
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading data
[ simnibs ]INFO: Info    : Reading nodes
[ simnibs ]INFO: Info    : Reading data
[ simnibs ]INFO: Info    : Done reading '/tmp/tmp2934Vq/sub-CMH090_TMS_1_cond.msh'
[ simnibs ]INFO: Info    : GmshRead[/tmp/tmp2934Vq/

[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Reading elements
[ simnibs ]INFO: Info    : Readi

[ simnibs ]INFO: Info    : Reading data
[ simnibs ]INFO: Info    : Reading data
[ simnibs ]INFO: Info    : Done reading '/tmp/tmp2934Vq/sub-CMH090_TMS_1-0014_Magstim_70mm_Fig8_nii_dadt.msh'
[ simnibs ]INFO: Info    : Generate[QS_dAdt]
Info    : Solve[QS_dAdt]                                                                  
[ simnibs ]INFO: Info    : N: 657584 - cg icc (null)
Info    : Solve[QS_dAdt]                                                                  
[ simnibs ]INFO: Info    : N: 657584 - cg icc (null)
Info    : Solve[QS_dAdt]                                                                  
[ simnibs ]INFO: Info    : N: 657584 - cg icc (null)
Info    : Solve[QS_dAdt]                                                                  
[ simnibs ]INFO: Info    : N: 657584 - cg icc (null)
Info    : Solve[QS_dAdt]                                                                  
[ simnibs ]INFO: Info    : N: 657584 - cg icc (null)
Info    : Solve[QS_dAdt]                     

[ simnibs ]INFO: Info    :  12 KSP Residual norm 4.162278363520e-02
[ simnibs ]INFO: Info    :  12 KSP Residual norm 4.745630432544e-02
[ simnibs ]INFO: Info    :   8 KSP Residual norm 7.525943967525e-02
[ simnibs ]INFO: Info    :   0 KSP Residual norm 3.774837663569e-01
[ simnibs ]INFO: Info    :   4 KSP Residual norm 8.182983093354e-02
[ simnibs ]INFO: Info    :  10 KSP Residual norm 5.539717726906e-02
[ simnibs ]INFO: Info    :  11 KSP Residual norm 5.988201105072e-02
[ simnibs ]INFO: Info    :   4 KSP Residual norm 1.068235300699e-01
[ simnibs ]INFO: Info    :   7 KSP Residual norm 8.106044256126e-02
[ simnibs ]INFO: Info    :   2 KSP Residual norm 1.156251656581e-01
[ simnibs ]INFO: Info    :   1 KSP Residual norm 1.302441659700e-01
[ simnibs ]INFO: Info    :  14 KSP Residual norm 3.173794234506e-02
[ simnibs ]INFO: Info    :   1 KSP Residual norm 1.361040128080e-01
[ simnibs ]INFO: Info    :   0 KSP Residual norm 3.963932100159e-01
[ simnibs ]INFO: Info    :   9 KSP Residual norm

[ simnibs ]INFO: Info    :   8 KSP Residual norm 8.130021881590e-02
[ simnibs ]INFO: Info    :  19 KSP Residual norm 2.730841903295e-02
[ simnibs ]INFO: Info    :   7 KSP Residual norm 8.086885554310e-02
[ simnibs ]INFO: Info    :  11 KSP Residual norm 6.782631063650e-02
[ simnibs ]INFO: Info    :  15 KSP Residual norm 3.916387517837e-02
[ simnibs ]INFO: Info    :   9 KSP Residual norm 7.673746948732e-02
[ simnibs ]INFO: Info    :   9 KSP Residual norm 6.531422037775e-02
[ simnibs ]INFO: Info    :  10 KSP Residual norm 6.939350061801e-02
[ simnibs ]INFO: Info    :  17 KSP Residual norm 3.471791799519e-02
[ simnibs ]INFO: Info    :   6 KSP Residual norm 9.781106279519e-02
[ simnibs ]INFO: Info    :  21 KSP Residual norm 1.826355433342e-02
[ simnibs ]INFO: Info    :  22 KSP Residual norm 1.016036041657e-02
[ simnibs ]INFO: Info    :  21 KSP Residual norm 1.382553058969e-02
[ simnibs ]INFO: Info    :  19 KSP Residual norm 1.890939381307e-02
[ simnibs ]INFO: Info    :  13 KSP Residual norm

[ simnibs ]INFO: Info    :  16 KSP Residual norm 4.288711688140e-02
[ simnibs ]INFO: Info    :  23 KSP Residual norm 1.669403446260e-02
[ simnibs ]INFO: Info    :  25 KSP Residual norm 1.377650959631e-02
[ simnibs ]INFO: Info    :  17 KSP Residual norm 3.847102028373e-02
[ simnibs ]INFO: Info    :  17 KSP Residual norm 2.911122327631e-02
[ simnibs ]INFO: Info    :  14 KSP Residual norm 4.867723712449e-02
[ simnibs ]INFO: Info    :  15 KSP Residual norm 3.982221282978e-02
[ simnibs ]INFO: Info    :  27 KSP Residual norm 6.579800713852e-03
[ simnibs ]INFO: Info    :  30 KSP Residual norm 2.524446684865e-03
[ simnibs ]INFO: Info    :  18 KSP Residual norm 3.438398153220e-02
[ simnibs ]INFO: Info    :  28 KSP Residual norm 8.786045101534e-03
[ simnibs ]INFO: Info    :  29 KSP Residual norm 6.876755812171e-03
[ simnibs ]INFO: Info    :  29 KSP Residual norm 4.219377798112e-03
[ simnibs ]INFO: Info    :  21 KSP Residual norm 1.363179763537e-02
[ simnibs ]INFO: Info    :  19 KSP Residual norm

[ simnibs ]INFO: Info    :  36 KSP Residual norm 3.486622467194e-03
[ simnibs ]INFO: Info    :  35 KSP Residual norm 3.468898649946e-03
[ simnibs ]INFO: Info    :  25 KSP Residual norm 1.425168675187e-02
[ simnibs ]INFO: Info    :  38 KSP Residual norm 5.909853415036e-04
[ simnibs ]INFO: Info    :  25 KSP Residual norm 1.162871806480e-02
[ simnibs ]INFO: Info    :  22 KSP Residual norm 2.200838359326e-02
[ simnibs ]INFO: Info    :  26 KSP Residual norm 1.233387537975e-02
[ simnibs ]INFO: Info    :  23 KSP Residual norm 1.693455857631e-02
[ simnibs ]INFO: Info    :  37 KSP Residual norm 2.293116920324e-03
[ simnibs ]INFO: Info    :  36 KSP Residual norm 3.228772733493e-03
[ simnibs ]INFO: Info    :  29 KSP Residual norm 4.784890956199e-03
[ simnibs ]INFO: Info    :  32 KSP Residual norm 5.061040014422e-03
[ simnibs ]INFO: Info    :  26 KSP Residual norm 1.148087006734e-02
[ simnibs ]INFO: Info    :  25 KSP Residual norm 1.424375959865e-02
[ simnibs ]INFO: Info    :  34 KSP Residual norm

[ simnibs ]INFO: Info    :  46 KSP Residual norm 2.336862327050e-04
[ simnibs ]INFO: Info    :  33 KSP Residual norm 3.711201148660e-03
[ simnibs ]INFO: Info    :  33 KSP Residual norm 4.168030423955e-03
[ simnibs ]INFO: Info    :  33 KSP Residual norm 3.235528499124e-03
[ simnibs ]INFO: Info    :  44 KSP Residual norm 1.407486587867e-03
[ simnibs ]INFO: Info    :  31 KSP Residual norm 5.507802719163e-03
[ simnibs ]INFO: Info    :  40 KSP Residual norm 2.771027010921e-03
[ simnibs ]INFO: Info    :  30 KSP Residual norm 6.054359615556e-03
[ simnibs ]INFO: Info    :  37 KSP Residual norm 2.354354835881e-03
[ simnibs ]INFO: Info    :  34 KSP Residual norm 4.019268075943e-03
[ simnibs ]INFO: Info    :  42 KSP Residual norm 1.843880302369e-03
[ simnibs ]INFO: Info    :  33 KSP Residual norm 3.442509445471e-03
[ simnibs ]INFO: Info    :  45 KSP Residual norm 9.950700898254e-04
[ simnibs ]INFO: Info    :  45 KSP Residual norm 1.102904679842e-03
[ simnibs ]INFO: Info    :  44 KSP Residual norm

[ simnibs ]INFO: Info    :  41 KSP Residual norm 1.882626488861e-03
[ simnibs ]INFO: Info    :  52 KSP Residual norm 2.656839854374e-04
[ simnibs ]INFO: Info    :  48 KSP Residual norm 5.606059011060e-04
[ simnibs ]INFO: Info    :  50 KSP Residual norm 4.143516697953e-04
[ simnibs ]INFO: Info    :  45 KSP Residual norm 9.913265540344e-04
[ simnibs ]INFO: Info    :  39 KSP Residual norm 2.970184612484e-03
[ simnibs ]INFO: Info    :  41 KSP Residual norm 1.618323924608e-03
[ simnibs ]INFO: Info    :  52 KSP Residual norm 2.787703533860e-04
[ simnibs ]INFO: Info    :  53 KSP Residual norm 2.442786815760e-04
[ simnibs ]INFO: Info    :  41 KSP Residual norm 1.558612988214e-03
[ simnibs ]INFO: Info    :  55 KSP Residual norm 8.134851343341e-05
[ simnibs ]INFO: Info    :  38 KSP Residual norm 2.858661663428e-03
[ simnibs ]INFO: Info    :  41 KSP Residual norm 2.130953796655e-03
[ simnibs ]INFO: Info    :  53 KSP Residual norm 2.297365356957e-04
[ simnibs ]INFO: Info    :  42 KSP Residual norm

[ simnibs ]INFO: Info    :  46 KSP Residual norm 8.461628367442e-04
[ simnibs ]INFO: Info    :  56 KSP Residual norm 1.474376128885e-04
[ simnibs ]INFO: Info    :  60 KSP Residual norm 8.868355980470e-05
[ simnibs ]INFO: Info    :  49 KSP Residual norm 4.837671575831e-04
[ simnibs ]INFO: Info    :  53 KSP Residual norm 2.346474088090e-04
[ simnibs ]INFO: Info    :  49 KSP Residual norm 4.495474439669e-04
[ simnibs ]INFO: Info    :  49 KSP Residual norm 4.195768425792e-04
[ simnibs ]INFO: Info    :  63 KSP Residual norm 2.544271195345e-05
[ simnibs ]INFO: Info    :  61 KSP Residual norm 5.736878565258e-05
[ simnibs ]INFO: Info    :  61 KSP Residual norm 5.355123897718e-05
[ simnibs ]INFO: Info    :  61 KSP Residual norm 5.638152101810e-05
[ simnibs ]INFO: Info    :  49 KSP Residual norm 5.102575826674e-04
[ simnibs ]INFO: Info    :  50 KSP Residual norm 4.498733513214e-04
[ simnibs ]INFO: Info    :  59 KSP Residual norm 7.265680767681e-05
[ simnibs ]INFO: Info    :  46 KSP Residual norm

[ simnibs ]INFO: Info    :  54 KSP Residual norm 1.819799260513e-04
[ simnibs ]INFO: Info    :  56 KSP Residual norm 1.444518566254e-04
[ simnibs ]INFO: Info    :  61 KSP Residual norm 6.335727261570e-05
[ simnibs ]INFO: Info    :  69 KSP Residual norm 2.129654331821e-05
[ simnibs ]INFO: Info    :  57 KSP Residual norm 1.087078718089e-04
[ simnibs ]INFO: Info    :  71 KSP Residual norm 1.192914793765e-05
[ simnibs ]INFO: Info    :  69 KSP Residual norm 2.371681637537e-05
[ simnibs ]INFO: Info    :  57 KSP Residual norm 1.010183031407e-04
[ simnibs ]INFO: Info    :  69 KSP Residual norm 2.049938410783e-05
[ simnibs ]INFO: Info    :  67 KSP Residual norm 1.315217307406e-05
[ simnibs ]INFO: Info    :  58 KSP Residual norm 9.698830083888e-05
[ simnibs ]INFO: Info    :  65 KSP Residual norm 3.323109534158e-05
[ simnibs ]INFO: Info    :  57 KSP Residual norm 1.097236376014e-04
[ simnibs ]INFO: Info    :  54 KSP Residual norm 2.191802112389e-04
[ simnibs ]INFO: Info    :  55 KSP Residual norm

[ simnibs ]INFO: Info    :  69 KSP Residual norm 2.801548218726e-05
[ simnibs ]INFO: Info    :  77 KSP Residual norm 7.891750929650e-06
[ simnibs ]INFO: Info    :  65 KSP Residual norm 2.095981360870e-05
[ simnibs ]INFO: Info    :  65 KSP Residual norm 3.608142996219e-05
[ simnibs ]INFO: Info    :  76 KSP Residual norm 1.206678711366e-05
[ simnibs ]INFO: Info    :  66 KSP Residual norm 1.834443049257e-05
[ simnibs ]INFO: Info    :  77 KSP Residual norm 8.321630703711e-06
[ simnibs ]INFO: Info    :  62 KSP Residual norm 4.785601634375e-05
[ simnibs ]INFO: Info    :  75 KSP Residual norm 2.498211557941e-06
[ simnibs ]INFO: Info    :  73 KSP Residual norm 1.621506847543e-05
[ simnibs ]INFO: Info    :  64 KSP Residual norm 2.733776308103e-05
[ simnibs ]INFO: Info    :  65 KSP Residual norm 2.392129158264e-05
[ simnibs ]INFO: Info    :  78 KSP Residual norm 6.535143359341e-06
[ simnibs ]INFO: Info    :  80 KSP Residual norm 4.307139474010e-06
[ simnibs ]INFO: Info    :  78 KSP Residual norm

[ simnibs ]INFO: Info    :  84 KSP Residual norm 3.012117648777e-06
[ simnibs ]INFO: Info    :  73 KSP Residual norm 1.391722919230e-05
[ simnibs ]INFO: Info    :  85 KSP Residual norm 2.082171059904e-06
[ simnibs ]INFO: Info    :  83 KSP Residual norm 5.289665396942e-07
[ simnibs ]INFO: Info    :  77 KSP Residual norm 8.428337492862e-06
[ simnibs ]INFO: Info    :  73 KSP Residual norm 8.356901353446e-06
[ simnibs ]INFO: Info    :  74 KSP Residual norm 4.796954084925e-06
[ simnibs ]INFO: Info    :  81 KSP Residual norm 4.574421411784e-06
[ simnibs ]INFO: Info    :  86 KSP Residual norm 1.640443544263e-06
[ simnibs ]INFO: Info    :  69 KSP Residual norm 2.042027266731e-05
[ simnibs ]INFO: Info    :  86 KSP Residual norm 1.310589070353e-06
[ simnibs ]INFO: Info    :  88 KSP Residual norm 1.047077216616e-06
[ simnibs ]INFO: Info    :  70 KSP Residual norm 8.229642256644e-06
[ simnibs ]INFO: Info    :  72 KSP Residual norm 7.609526320216e-06
[ simnibs ]INFO: Info    :  85 KSP Residual norm

[ simnibs ]INFO: Info    :  81 KSP Residual norm 3.071592918602e-06
[ simnibs ]INFO: Info    :  92 KSP Residual norm 4.673717162074e-07
[ simnibs ]INFO: Info    :  76 KSP Residual norm 1.024204843914e-05
[ simnibs ]INFO: Info    :  85 KSP Residual norm 2.117377247826e-06
[ simnibs ]INFO: Info    :  81 KSP Residual norm 3.743524948586e-06
[ simnibs ]INFO: Info    :  82 KSP Residual norm 2.417544413928e-06
[ simnibs ]INFO: Info    :  89 KSP Residual norm 9.917007051576e-07
[ simnibs ]INFO: Info    :  94 KSP Residual norm 3.803269721870e-07
[ simnibs ]INFO: Info    :  94 KSP Residual norm 3.338096309266e-07
[ simnibs ]INFO: Info    :  96 KSP Residual norm 2.329067915246e-07
[ simnibs ]INFO: Info    :  78 KSP Residual norm 2.491202109687e-06
[ simnibs ]INFO: Info    :  92 KSP Residual norm 1.599094573645e-07
[ simnibs ]INFO: Info    :  82 KSP Residual norm 3.465893666246e-06
[ simnibs ]INFO: Info    :  94 KSP Residual norm 3.257167975014e-07
[ simnibs ]INFO: Info    :  80 KSP Residual norm

[ simnibs ]INFO: Info    :  85 KSP Residual norm 1.284454275432e-06
[ simnibs ]INFO: Info    : 102 KSP Residual norm 7.026735547804e-08
[ simnibs ]INFO: Info    :  87 KSP Residual norm 1.155210284466e-06
[ simnibs ]INFO: Info    : 102 KSP Residual norm 7.073240772158e-08
[ simnibs ]INFO: Info    :  97 KSP Residual norm 2.283505987958e-07
[ simnibs ]INFO: Info    :  84 KSP Residual norm 2.439771265280e-06
[ simnibs ]INFO: Info    :  90 KSP Residual norm 5.445614709483e-07
[ simnibs ]INFO: Info    :  89 KSP Residual norm 6.141821499580e-07
[ simnibs ]INFO: Info    : 100 KSP Residual norm 6.025250009931e-08
[ simnibs ]INFO: Info    : 104 KSP Residual norm 4.142538142232e-08
[ simnibs ]INFO: Info    : 101 KSP Residual norm 7.853346839479e-08
[ simnibs ]INFO: Info    :  90 KSP Residual norm 7.642441869084e-07
[ simnibs ]INFO: Info    :  90 KSP Residual norm 6.116546136760e-07
[ simnibs ]INFO: Info    :  94 KSP Residual norm 3.654658363289e-07
[ simnibs ]INFO: Info    : 102 KSP Residual norm

[ simnibs ]INFO: Info    :  97 KSP Residual norm 1.981182174600e-07
[ simnibs ]INFO: Info    :  92 KSP Residual norm 3.528095533559e-07
[ simnibs ]INFO: Info    : 108 KSP Residual norm 1.832137337638e-08
[ simnibs ]INFO: Info    : 105 KSP Residual norm 4.375949141250e-08
[ simnibs ]INFO: Info    :  98 KSP Residual norm 1.157517701781e-07
[ simnibs ]INFO: Info    : 112 KSP Residual norm 8.043932966072e-09
[ simnibs ]INFO: Info    : 109 KSP Residual norm 1.558620598029e-08
[ simnibs ]INFO: Info    :  97 KSP Residual norm 1.111606119660e-07
[ simnibs ]INFO: Info    :  93 KSP Residual norm 4.059879837918e-07
[ simnibs ]INFO: Info    : 111 KSP Residual norm 1.049854576901e-08
[ simnibs ]INFO: Info    :  98 KSP Residual norm 1.481715029688e-07
[ simnibs ]INFO: Info    : 102 KSP Residual norm 7.550708238619e-08
[ simnibs ]INFO: Info    :  95 KSP Residual norm 3.205226829780e-07
[ simnibs ]INFO: Info    : 111 KSP Residual norm 1.159811244200e-08
[ simnibs ]INFO: Info    :  98 KSP Residual norm

[ simnibs ]INFO: Info    : 118 KSP Residual norm 2.471636304152e-09
[ simnibs ]INFO: Info    : 116 KSP Residual norm 3.576559340391e-09
[ simnibs ]INFO: Info    : 106 KSP Residual norm 2.857077060231e-08
[ simnibs ]INFO: Info    : 117 KSP Residual norm 2.135582347160e-09
[ simnibs ]INFO: Info    : 119 KSP Residual norm 2.163700755772e-09
[ simnibs ]INFO: Info    : 113 KSP Residual norm 7.886378547601e-09
[ simnibs ]INFO: Info    : 102 KSP Residual norm 8.591071421387e-08
[ simnibs ]INFO: Info    : 110 KSP Residual norm 1.216483386837e-08
[ simnibs ]INFO: Info    : 106 KSP Residual norm 3.346926958759e-08
[ simnibs ]INFO: Info    : 118 KSP Residual norm 2.263109127026e-09
[ simnibs ]INFO: Info    : 106 KSP Residual norm 3.096255020093e-08
[ simnibs ]INFO: Info    : 101 KSP Residual norm 1.005847906969e-07
[ simnibs ]INFO: Info    : 101 KSP Residual norm 6.847617889890e-08
[ simnibs ]INFO: Info    : 105 KSP Residual norm 2.668873995458e-08
[ simnibs ]INFO: Info    : 121 KSP Residual norm

[ simnibs ]INFO: Info    : 126 KSP Residual norm 5.090902991746e-10
[ simnibs ]INFO: Info    : 121 KSP Residual norm 1.652923068478e-09
[ simnibs ]INFO: Info    : 125 KSP Residual norm 4.979328378207e-10
[ simnibs ]INFO: Info    : 127 KSP Residual norm 4.367329671895e-10
[ simnibs ]INFO: Info    : 118 KSP Residual norm 2.670694636607e-09
[ simnibs ]INFO: Info    : 109 KSP Residual norm 2.042011928796e-08
[ simnibs ]INFO: Info    : 126 KSP Residual norm 3.841920358123e-10
[ simnibs ]INFO: Info    : 114 KSP Residual norm 5.386608198992e-09
[ simnibs ]INFO: Info    : 114 KSP Residual norm 6.203511003004e-09
[ simnibs ]INFO: Info    : 129 KSP Residual norm 1.816693156057e-10
[ simnibs ]INFO: Info    : 113 KSP Residual norm 3.648906559694e-09
[ simnibs ]INFO: Info    : 109 KSP Residual norm 1.953438651043e-08
[ simnibs ]INFO: Info    : 125 KSP Residual norm 5.700101307633e-10
[ simnibs ]INFO: Info    : 109 KSP Residual norm 1.635264447273e-08
[ simnibs ]INFO: Info    : 115 KSP Residual norm

[ simnibs ]INFO: Info    : 133 KSP Residual norm 1.111519730107e-10
[ simnibs ]INFO: Info    : 116 KSP Residual norm 4.475768157329e-09
[ simnibs ]INFO: Info    : 135 KSP Residual norm 6.162188752566e-11
[ simnibs ]INFO: Info    : 126 KSP Residual norm 4.440483519646e-10
[ simnibs ]INFO: Info    : 122 KSP Residual norm 1.008593928941e-09
[ simnibs ]INFO: Info    : 134 KSP Residual norm 6.992219890641e-11
[ simnibs ]INFO: Info    : 121 KSP Residual norm 7.572920639374e-10
[ simnibs ]INFO: Info    : 133 KSP Residual norm 1.096569190405e-10
[ simnibs ]INFO: Info    : 122 KSP Residual norm 1.362503260655e-09
[ simnibs ]INFO: Info    : 137 KSP Residual norm 4.484950373648e-11
[ simnibs ]INFO: Info    : 117 KSP Residual norm 2.636471540327e-09
[ simnibs ]INFO: Info    : 123 KSP Residual norm 9.034397317791e-10
[ simnibs ]INFO: Info    : 135 KSP Residual norm 6.112419737496e-11
[ simnibs ]INFO: Info    : 130 KSP Residual norm 3.212393630581e-10
[ simnibs ]INFO: Info    : 117 KSP Residual norm

[ simnibs ]INFO: Info    : 128 KSP Residual norm 1.683229145946e-10
[ simnibs ]INFO: Info    : 129 KSP Residual norm 2.749611862166e-10
[ simnibs ]INFO: Info    : 124 KSP Residual norm 6.586730565048e-10
[ simnibs ]INFO: Info    : 129 KSP Residual norm 3.256657388799e-10
[ simnibs ]INFO: Execution finished
[ simnibs ]INFO: Info    : 130 KSP Residual norm 1.518365967227e-10
[ simnibs ]INFO: Info    : 124 KSP Residual norm 1.065604804241e-09
[ simnibs ]INFO: Info    : 124 KSP Residual norm 1.067892425046e-09
[ simnibs ]INFO: Info    : 134 KSP Residual norm 5.944687829926e-11
[ simnibs ]INFO: Info    : 138 KSP Residual norm 3.680332575645e-11
[ simnibs ]INFO: Info    : 138 iterations
[ simnibs ]INFO: Info    : SaveSolution[QS_dAdt]
[ simnibs ]INFO: Info    : (Wall = 285.027s, CPU = 283.718s, Mem = 4244.28Mb)
[ simnibs ]INFO: E n d   P r o c e s s i n g
[ simnibs ]INFO: Info    : 129 KSP Residual norm 1.407612982096e-10
[ simnibs ]INFO: Info    : 130 KSP Residual norm 2.086289963533e-10
[ 

[ simnibs ]INFO: Info    : 138 iterations
[ simnibs ]INFO: Info    : SaveSolution[QS_dAdt]
[ simnibs ]INFO: Info    : (Wall = 294.386s, CPU = 293.611s, Mem = 4244.26Mb)
[ simnibs ]INFO: E n d   P r o c e s s i n g
[ simnibs ]INFO: Info    : 138 KSP Residual norm 3.538140792990e-11
[ simnibs ]INFO: Info    : 138 iterations
[ simnibs ]INFO: Info    : SaveSolution[QS_dAdt]
[ simnibs ]INFO: Info    : Stopped (Fri Apr 26 16:14:58 2019, Wall = 292.944s, CPU = 291.417s, Mem = 4244.28Mb)
[ simnibs ]INFO: Info    : (Wall = 294.174s, CPU = 293.022s, Mem = 4244.15Mb)
[ simnibs ]INFO: E n d   P r o c e s s i n g
[ simnibs ]INFO: Info    : Stopped (Fri Apr 26 16:14:58 2019, Wall = 294.839s, CPU = 293.796s, Mem = 4244.26Mb)
[ simnibs ]INFO: Execution finished
[ simnibs ]INFO: Info    : Stopped (Fri Apr 26 16:14:58 2019, Wall = 294.642s, CPU = 293.233s, Mem = 4244.15Mb)
[ simnibs ]INFO: Execution finished
[ simnibs ]INFO: Execution finished
[ simnibs ]INFO: Execution finished
[ simnibs ]INFO: Executi

542.239037991


In [23]:
observations = -observations

In [25]:
hist_data = HistoricalData(dim = 3, num_derivatives= 0)
hist_data.append_sample_points([SamplePoint(inp,o,0.0) 
                                for o,inp in 
                                zip(observations,init_pts)])


In [26]:
#Set up model specifications
prior = DefaultPrior(n_dims = 3 + 2, num_noise=1)
gp_ll = GaussianProcessLogLikelihoodMCMC(historical_data=hist_data,
                                         derivatives=[], prior=prior,
                                         chain_length=1000, burnin_steps=2000,
                                         n_hypers=2**4, noisy=False)
gp_ll.train()

In [27]:
#Set up optimizer
sgd_params = cGDParams(num_multistarts=200, max_num_steps=50,
                      max_num_restarts=2, num_steps_averaged=4,
                      gamma=0.7, pre_mult=1.0, max_relative_change=0.5,
                      tolerance=1.0e-10)

In [44]:
#Set up optimization parametes
from IPython.display import clear_output, display
num_iters = 50
num_samples = int(ncpus*1.3)

In [45]:
def gen_sample_from_qei(gp,search_domain,sgd_params,num_samples, num_mc=1e4, lhc_iter=2e4):
    
    qEI = ExpectedImprovement(gaussian_process=gp, num_mc_iterations=int(num_mc))
    optimizer = cGDOpt(search_domain, qEI, sgd_params, int(lhc_iter))
    points_to_sample = meio(optimizer, None, num_samples, use_gpu=False, which_gpu=0,
                      max_num_threads=8)
    qEI.set_current_point(points_to_sample[0])
    
    return points_to_sample, qEI.compute_expected_improvement()

In [48]:
best_point_history = []
for i in np.arange(0,num_iters):
    
    #Optimize qEI and pick samples
    points_to_sample, ei = gen_sample_from_qei(gp_ll.models[0],
                                               c_search_domain, sgd_params=sgd_params,
                                               num_samples=num_samples, num_mc=2**10)
    
    #Collect observations
    sampled_points = -f.evaluate(points_to_sample)
    evidence = [SamplePoint(c,v,0.0) for c,v in zip(points_to_sample, sampled_points)]
    
    #Update model
    gp_ll.add_sampled_points(evidence)
    gp_ll.train()
    
    #Pull model and pull values
    gp = gp_ll.models[0]
    min_point = np.argmin(gp._points_sampled_value)
    min_val = np.min(gp._points_sampled_value)
    best_coord = gp.get_historical_data_copy().points_sampled[min_point]
    
    clear_output()
    print('Recommended Points:')
    print(points_to_sample)
    print('Expected Improvement: {}'.format(ei))
    print('Current Best:')
    print('f(x*)=',min_val)
    print('Coord:', best_coord)
    
    best_point_history.append(min_val)

Recommended Points:
[[-3.41717108e+00 -1.38474796e-01  1.36363716e+02]
 [ 6.35021787e+00  1.70156497e+01  9.37690190e+01]
 [ 2.90076500e+01  2.78538462e+01  8.77297149e+00]
 [ 2.80575849e+01 -7.52749833e+00  3.60256187e+01]
 [ 5.91964109e+00  3.73052597e+00  1.18923099e+02]
 [-8.63318924e+00  1.11079295e+01  4.88326049e+01]
 [ 1.55585938e+01 -1.02555772e+00  1.62063422e+02]
 [ 8.22779890e-01 -8.21376821e-01  7.03603071e+00]
 [ 1.65091303e+00 -8.58093727e+00  2.64030644e+01]
 [ 2.57771091e+01 -5.93440475e+00  1.04166824e+02]
 [ 4.44502440e+00  3.48400747e+01  1.13575240e+02]
 [-2.87805056e+00  3.39862381e+00  1.72412585e+02]
 [ 1.72004122e+01 -3.88434616e+00  1.66441535e+02]
 [ 1.69436039e+01  4.57247399e+00  8.79119903e+01]
 [-4.38331987e+00  8.88195348e+00  1.43422487e+02]
 [ 1.72165658e+01 -8.43848898e+00  1.64618252e+01]
 [ 7.60091948e+00  1.98176568e+01  1.03007641e+02]
 [ 1.21526358e+00  2.19944907e+00  5.23628059e+01]
 [-5.04151204e+00  1.41269781e+01  6.41187286e+00]]
Expected I